### ISSUE TITLE
Access to docker image unauthorized

### ISSUE THREAD

**Issue by GuilhermeAumo** [johannestang/llamaxing#1]
Hello! I see this repo is quite new, but it seems really nice!

I have just tried to run the docker compose from the examples, but the image path `quay.io/johannestang/llamaxing` is not public, so I can't access it. I suppose it was intended to be public, so you should probably change it's access rights.

Anyway, good work!

On another note, I changed the docker compose to 
```
build:
      context: .
      dockerfile: Dockerfile
```

But I am getting the error `IsADirectoryError: [Errno 21] Is a directory: 'models.json'` after the container is up. This is probably my mistake, so I will keeping looking at it.

**Comment by johannestang** [comment]
Thanks for letting me know. The image should be public now.

Regarding the error you get: My guess would be that the issue stems from the `.env` file. If you haven't set up that file correctly and configured a valid value for `PROVIDER` then the volume mount will fail.
